storage:
  store: local
  path: '/data'

artifactIndex:
  index: zookeeper
  connectionString: '192.168.99.100:2181'
  
repositories:
- id: snapshot
  type: java-snapshot
  storageConfiguration: 
    uploadPath: 'java-snapshots'
    limit: 20G
    
- id: release
  type: java-release
  storageConfiguration:
    uploadPath: 'java-releases'
    limit: 10G

- id: download
  type: java-download
  storageConfiguration:
    uploadPath: 'java-proxy'
    limit: 40G
  proxy:
  - https://repo.maven.apache.org/maven2
  